fix(autosubmit): Update in case checkout already exists
We're seeing this in every
http://jenkins.qa.suse.de/job/trigger-openQA_in_openQA-TW/ pipeline:
```
[debug] ### osc co --server-side-source-service-files devel:openQA/openQA
error: 'devel:openQA/openQA' is already an initialized osc working copy
Retrying up to 3 more times after sleeping 3s …
error: 'devel:openQA/openQA' is already an initialized osc working copy
Retrying up to 2 more times after sleeping 6s …
error: 'devel:openQA/openQA' is already an initialized osc working copy
Retrying up to 1 more times after sleeping 12s …
error: 'devel:openQA/openQA' is already an initialized osc working copy
+ sync_changesrevision devel:openQA openQA 16015723
```

The osc checkout exists in a permanent Jenkins workspace, so in that case
we only need to make sure the checkout is uptodate.

This fix will not only make the pipeline a bit faster, but also avoid
conflicts in case there have been changes, specifically to
the `_servicedata` file.

Related issue: https://progress.opensuse.org/issues/207582